const router = require('express').Router()
const userHandlers = require('../handlers/user')
const messageHandlers = require('../handlers/message')

router.post("/signUp", userHandlers.signUpUser)
router.post("/LogIn", userHandlers.logIn)
router.post("/sendMessage", userHandlers.checkCookie, messageHandlers.sendMessage)
router.get("/inbox", userHandlers.checkCookie, messageHandlers.getInbox)
router.get("/sent", userHandlers.checkCookie, messageHandlers.getSentMessages)
router.post("/markMsgAsRead", userHandlers.checkCookie, messageHandlers.markMsgAsRead)
router.post("/deleteMessage", userHandlers.checkCookie, messageHandlers.deleteMessage)
router.post("/get-users", userHandlers.getUsers)
router.get("/check", userHandlers.checkCookie, userHandlers.islogged)
router.get("/logout", userHandlers.logOut)
module.exports = router
